### ISSUE TITLE
Peerswap web on Umbrel App Store?

### ISSUE THREAD

**Issue by thool2b3** [Impa10r/peerswap-web#11]
Hi Vlad, 
thank you for your efforts and for providing the Peerswap Web. 
I would like to use your solution on an Umbrel Home but I am not familiar with docker installation and I don't want to break something. 
I just read in this article [PeerSwap on an Umbrel Home](https://github.com/zapomatic/zapomatic/blob/main/PeerSwap.md) that you are working on an Umbrel App store app for theePeerSwap Web UI. Could you please give us an idea when this might be ready.
Thanks a lot, 
Thomas

**Comment by Impa10r** [comment]
Hello Thomas. I submitted [PeerSwap for Umbrel](https://github.com/getumbrel/umbrel-apps/pull/932) on January 9, some 1.5 months ago. They still did not review it. I don't know how to push this process, I offered my help there and in Discord. Maybe you can leave a comment to ask this question? Meanwhile, I use PS on my Umbrel with Elements Core installed via App Store and with PeerSwap and PeerSwap web both installed manually with Go.

**Comment by thool2b3** [comment]
Thank you, Vlad. 
I posted a comment and asked @smolgrrr about their progress.
Hope your solution will make it soon in the official Umbrel App store since I am not familiar installing manually.
