### ISSUE TITLE
Latest docker image fails with permission denied

### ISSUE THREAD

**Issue by zapomatic** [Impa10r/peerswap-web#16]
Running from your latest umbrel app settings: https://github.com/Impa10r/umbrel-apps/blob/master/peerswap/docker-compose.yml

App fails to start:

```
2024/03/23 20:14:24 open /home/peerswap/.peerswap/psweb.log: permission denied
2024/03/23 20:14:28 open /home/peerswap/.peerswap/log: permission denied
```

**Comment by Impa10r** [comment]
That's because your .peerswap is owned by root and all files in it. See [this](https://github.com/Impa10r/peerswap-web/blob/main/CHANGELOG.md#118) to fix.

**Comment by zapomatic** [comment]
Looks like somehow this node was in the following state:

`/home/umbrel/umbrel/app-data/peerswap/data` was owned by root and was empty
`/home/umbrel/.peerswap` was owned by umbrel and contained all the config files.
resolved by running:

```
sudo chown umbrel:umbrel /home/umbrel/umbrel/app-data/peerswap/data
cp ~/.peerswap/* /home/umbrel/umbrel/app-data/peerswap/data/
sudo /home/umbrel/scripts/app restart peerswap
```
