### ISSUE TITLE
Peerpartner should be linked to amboss.space, not mempool.space 

### ISSUE THREAD

**Issue by M1ch43lV** [Impa10r/peerswap-web#4]
Hi Impalor,
great web gui, thanks very much! 
Hopefully your work will contribute that more and more noderunners will use the peerswap service!
Would it be possible that you link the pubkey of a node to amboss.space instead of mempool.space?
![Screenshot_20240101_183116_Samsung Internet](https://github.com/Impa10r/peerswap-web/assets/100045502/3a2c7bf9-8c05-4dd0-9828-8ef0e1a009a6)

**Comment by Impa10r** [comment]
>  Would it be possible that you link the pubkey of a node to amboss.space instead of mempool.space?

Hi, thanks for your feedback and for testing it. This can certainly be done, but it won't work with testnet. Amboss only lists mainnet nodes, but I can add this choice with this caveat.

I will let you know when I update it.

**Comment by M1ch43lV** [comment]
Do you recommend that peerswap should only be used on testnet?

**Comment by Impa10r** [comment]
> Do you recommend that peerswap should only be used on testnet?

For now, yes. The guys are still ironing out the bugs. For example, you can initiate a swap and pay liquid fee for two transactions, but it will fail. I recommend you first play with it on testnet to be aware of such situations. You can set it up easily in VirtualBox with several nodes as .lnd, .lnd2 and .peerswap, .peerswap2 etc folders.

**Comment by Impa10r** [comment]
@M1ch43lV I added the option, please clone and rebuild, then go to Settings page to switch to it. Let me know if you have any problems.

**Comment by M1ch43lV** [comment]
Thanks for the update! It is working. 
Just the title has a little orthographic error: liqiud stats

**Comment by Impa10r** [comment]
> Thanks for the update! It is working. Just the title has a little orthographic error: liqiud stats

Which screen? Cannot see...

**Comment by M1ch43lV** [comment]
![image](https://github.com/Impa10r/peerswap-web/assets/100045502/23fbaa14-ab11-42d2-995c-3a87626fe6ce)
![image](https://github.com/Impa10r/peerswap-web/assets/100045502/d562d342-f185-4e89-9c06-6985b1eb9f3a)

**Comment by Impa10r** [comment]
@M1ch43lV they show sats. Cool that you have some live peers!

**Comment by M1ch43lV** [comment]
Sorry, I mean the word "Liqiud". Should be "Liquid"

**Comment by Impa10r** [comment]
@M1ch43lV ah yes! Good catch! Fixed

**Comment by Impa10r** [comment]
Closing this issue for now.
