### ISSUE TITLE
invalid go version

### ISSUE THREAD

**Issue by tuganode** [Impa10r/peerswap-web#5]
Hi, running in debian linux kernel 6+ (MXlinux) raise this message:

"/home/elements/peerswap-web/go.mod:3: invalid go version '1.21.5': must match format 1.23"

**Comment by Impa10r** [comment]
> "/home/elements/peerswap-web/go.mod:3: invalid go version '1.21.5': must match format 1.23"

Hello. Are you running the latest version of Go? 1.21.5 should not produce this error. If you cannot upgrade, try this:
Run 'go version' and put the value you get into go.mod file on line 3.

**Comment by tuganode** [comment]
Ok, that's works!  thanks!
