### ISSUE TITLE
Counting fees is missing when wallet is locked of the peer partner

### ISSUE THREAD

**Issue by M1ch43lV** [Impa10r/peerswap-web#7]
Hello Impalor! Thanks for the great tool, it helps a lot to have an overview of successful and unsuccessful swaps.
I have following suggestion for psweb:

1. Cumulative fee statistics for all paid fees (successful and unsuccessful ones) on one page showing all fees occurred with date and time.psw
2. Counting paid fees of unsuccessful swaps if possible. Example log which occurred with one of my peer partner whose wallet was locked:
![image](https://github.com/Impa10r/peerswap-web/assets/100045502/126c3a84-08dc-4169-87f9-61d1d83ac01e)
```2024/01/26 09:20:04 [INFO] [Swap:8eaa42137d7dca61371a4d36cadb080b3c27531e1920e2eb1306bdafbb0255b8] Start new swap-out: peer: 039cdd937f8d83fb2f78c8d7ddc92ae28c9dbb5c4827181cfc80df60dee1b7bf19 chanId: 772654:1878:0 initiator: 0335bd24a733d623205f30452c485de9c39ac3135f57679574a49a3add6bb1a050 amount 2000000
2024/01/26 09:20:07 [INFO] [Swap:8eaa42137d7dca61371a4d36cadb080b3c27531e1920e2eb1306bdafbb0255b8] Paid Feeinvoice of 306 sats
2024/01/26 09:20:07 [INFO] [Swap:8eaa42137d7dca61371a4d36cadb080b3c27531e1920e2eb1306bdafbb0255b8] Swap canceled. Reason: -13:Error: Please enter the wallet passphrase with walletpassphrase first.
2024/01/26 09:20:07 [INFO] [Swap:8eaa42137d7dca61371a4d36cadb080b3c27531e1920e2eb1306bdafbb0255b8] Warning: Paid swap-out prepayment, but swap canceled before receiving opening transaction```

**Comment by Impa10r** [comment]
Yes, I agree this would be useful, but the swaps statistics is done by peerswap. Web UI can merely display it. Currently, only lightning rebates are accounted for. There is an open issue to add chain fees to the recorded stats: https://github.com/ElementsProject/peerswap/issues/266

**Comment by Impa10r** [comment]
Please mention the unreported prepaid fee example at the link above
