### ISSUE TITLE
Caveat of peg-in for pruned nodes 

### ISSUE THREAD

**Issue by M1ch43lV** [Impa10r/peerswap-web#8]
Hi Impalor, 
it would be good to point out in your readme that owners of pruned node have to modify the procedure of getting the raw tx of sending btc to the elements btc address during the pegging-in. 

bitcoin-cli  getrawtransaction <yourTXID> only working for bitcoin **full** nodes with txindex=1 enabled. 

For pruned nodes you get the raw tx by using mempool.space entering <yourTXID>, then clicking on transaction hex (see snapshot)

<img width="571" alt="image" src="https://github.com/Impa10r/peerswap-web/assets/100045502/f69bd1e1-0956-498e-b0d4-90240805ca46">

**Comment by Impa10r** [comment]
Thanks for pointing this out. I think there are generally many such problems with pruned nodes. I don't run them. Feel free to make a pull request.
