### ISSUE TITLE
Add oRate, oBase and iRate, iBase

### ISSUE THREAD

**Issue by M1ch43lV** [Impa10r/peerswap-web#9]
To calculate whether swapping might be profitable it would be suitable to see the base and fee rates to and from my peer partners.

This is what happened accidentally: 

Source Node A: base fee 0, fee rate 550ppm to peer => swapping OUT 4M sats
Target Node B: base 0, fee rate 20ppm => swapping IN 4M  

So I gave up a revenue of potentially 4×550=2200sats and swapped to a channel for which I only can gain '20ppm 4×20=80sats. This definitely means a loss for me. 
If I had seen this beforehand, I wouldn't have made this mistake

Depending from the incoming rate I can also decide if it is better to rebalance the classical way

**Comment by Impa10r** [comment]
To make a decision for a swap, instantaneous fee rates are not sufficient and can be misleading. You need to see the full history of the channel: direct and assisted income over one week, one month, etc. Tools like LNDg specifically exist for this purpose. PeerSwap Web UI does not have API access to LND nor a goal to become another LNDg.
